/* tslint:disable */
/* eslint-disable */
/**
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.22
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../../configuration';
// URLSearchParams not necessarily used
// @ts-ignore
import { URL, URLSearchParams } from 'url';
import FormData from 'form-data'
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../../base';
// @ts-ignore
import { GetEInvoiceRejectionReasonResponse } from '../../src/models';
// @ts-ignore
import { SendEInvoiceRequest } from '../../src/models';
// @ts-ignore
import { SendEInvoiceResponse } from '../../src/models';
// @ts-ignore
import { VerifyEInvoiceXmlErrorResponse } from '../../src/models';
// @ts-ignore
import { VerifyEInvoiceXmlResponse } from '../../src/models';
/**
 * IssuedEInvoicesApi - axios parameter creator
 * @export
 */
export const IssuedEInvoicesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get e-invoice rejection reason
         * @summary Get e-invoice rejection reason
         * @param {number} companyId The ID of the company.
         * @param {number} documentId The ID of the document.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEInvoiceRejectionReason: async (companyId: number, documentId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyId' is not null or undefined
            assertParamExists('getEInvoiceRejectionReason', 'companyId', companyId)
            // verify required parameter 'documentId' is not null or undefined
            assertParamExists('getEInvoiceRejectionReason', 'documentId', documentId)
            const localVarPath = `/c/{company_id}/issued_documents/{document_id}/e_invoice/error_reason`
                .replace(`{${"company_id"}}`, encodeURIComponent(String(companyId)))
                .replace(`{${"document_id"}}`, encodeURIComponent(String(documentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2AuthenticationCodeFlow required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2AuthenticationCodeFlow", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Downloads the e-invoice in XML format.
         * @summary Get e-invoice XML
         * @param {number} companyId The ID of the company.
         * @param {number} documentId The ID of the document.
         * @param {boolean} [includeAttachment] Include the attachment to the XML e-invoice.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEInvoiceXml: async (companyId: number, documentId: number, includeAttachment?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyId' is not null or undefined
            assertParamExists('getEInvoiceXml', 'companyId', companyId)
            // verify required parameter 'documentId' is not null or undefined
            assertParamExists('getEInvoiceXml', 'documentId', documentId)
            const localVarPath = `/c/{company_id}/issued_documents/{document_id}/e_invoice/xml`
                .replace(`{${"company_id"}}`, encodeURIComponent(String(companyId)))
                .replace(`{${"document_id"}}`, encodeURIComponent(String(documentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2AuthenticationCodeFlow required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2AuthenticationCodeFlow", [], configuration)

            if (includeAttachment !== undefined) {
                localVarQueryParameter['include_attachment'] = includeAttachment;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Sends the e-invoice to SDI.
         * @summary Send the e-invoice
         * @param {number} companyId The ID of the company.
         * @param {number} documentId The ID of the document.
         * @param {SendEInvoiceRequest} [sendEInvoiceRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendEInvoice: async (companyId: number, documentId: number, sendEInvoiceRequest?: SendEInvoiceRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyId' is not null or undefined
            assertParamExists('sendEInvoice', 'companyId', companyId)
            // verify required parameter 'documentId' is not null or undefined
            assertParamExists('sendEInvoice', 'documentId', documentId)
            const localVarPath = `/c/{company_id}/issued_documents/{document_id}/e_invoice/send`
                .replace(`{${"company_id"}}`, encodeURIComponent(String(companyId)))
                .replace(`{${"document_id"}}`, encodeURIComponent(String(documentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2AuthenticationCodeFlow required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2AuthenticationCodeFlow", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['User-Agent'] = 'FattureInCloud/2.0.6/TypeScript-SDK';


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sendEInvoiceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Verifies the e-invoice XML format. Checks if all of the mandatory fields are filled and compliant to the right format.
         * @summary Verify e-invoice XML
         * @param {number} companyId The ID of the company.
         * @param {number} documentId The ID of the document.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyEInvoiceXml: async (companyId: number, documentId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyId' is not null or undefined
            assertParamExists('verifyEInvoiceXml', 'companyId', companyId)
            // verify required parameter 'documentId' is not null or undefined
            assertParamExists('verifyEInvoiceXml', 'documentId', documentId)
            const localVarPath = `/c/{company_id}/issued_documents/{document_id}/e_invoice/xml_verify`
                .replace(`{${"company_id"}}`, encodeURIComponent(String(companyId)))
                .replace(`{${"document_id"}}`, encodeURIComponent(String(documentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2AuthenticationCodeFlow required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2AuthenticationCodeFlow", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IssuedEInvoicesApi - functional programming interface
 * @export
 */
export const IssuedEInvoicesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IssuedEInvoicesApiAxiosParamCreator(configuration)
    return {
        /**
         * Get e-invoice rejection reason
         * @summary Get e-invoice rejection reason
         * @param {number} companyId The ID of the company.
         * @param {number} documentId The ID of the document.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEInvoiceRejectionReason(companyId: number, documentId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetEInvoiceRejectionReasonResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEInvoiceRejectionReason(companyId, documentId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Downloads the e-invoice in XML format.
         * @summary Get e-invoice XML
         * @param {number} companyId The ID of the company.
         * @param {number} documentId The ID of the document.
         * @param {boolean} [includeAttachment] Include the attachment to the XML e-invoice.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEInvoiceXml(companyId: number, documentId: number, includeAttachment?: boolean, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEInvoiceXml(companyId, documentId, includeAttachment, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Sends the e-invoice to SDI.
         * @summary Send the e-invoice
         * @param {number} companyId The ID of the company.
         * @param {number} documentId The ID of the document.
         * @param {SendEInvoiceRequest} [sendEInvoiceRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendEInvoice(companyId: number, documentId: number, sendEInvoiceRequest?: SendEInvoiceRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SendEInvoiceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendEInvoice(companyId, documentId, sendEInvoiceRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Verifies the e-invoice XML format. Checks if all of the mandatory fields are filled and compliant to the right format.
         * @summary Verify e-invoice XML
         * @param {number} companyId The ID of the company.
         * @param {number} documentId The ID of the document.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verifyEInvoiceXml(companyId: number, documentId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VerifyEInvoiceXmlResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.verifyEInvoiceXml(companyId, documentId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * IssuedEInvoicesApi - factory interface
 * @export
 */
export const IssuedEInvoicesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IssuedEInvoicesApiFp(configuration)
    return {
        /**
         * Get e-invoice rejection reason
         * @summary Get e-invoice rejection reason
         * @param {number} companyId The ID of the company.
         * @param {number} documentId The ID of the document.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEInvoiceRejectionReason(companyId: number, documentId: number, options?: any): AxiosPromise<GetEInvoiceRejectionReasonResponse> {
            return localVarFp.getEInvoiceRejectionReason(companyId, documentId, options).then((request) => request(axios, basePath));
        },
        /**
         * Downloads the e-invoice in XML format.
         * @summary Get e-invoice XML
         * @param {number} companyId The ID of the company.
         * @param {number} documentId The ID of the document.
         * @param {boolean} [includeAttachment] Include the attachment to the XML e-invoice.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEInvoiceXml(companyId: number, documentId: number, includeAttachment?: boolean, options?: any): AxiosPromise<string> {
            return localVarFp.getEInvoiceXml(companyId, documentId, includeAttachment, options).then((request) => request(axios, basePath));
        },
        /**
         * Sends the e-invoice to SDI.
         * @summary Send the e-invoice
         * @param {number} companyId The ID of the company.
         * @param {number} documentId The ID of the document.
         * @param {SendEInvoiceRequest} [sendEInvoiceRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendEInvoice(companyId: number, documentId: number, sendEInvoiceRequest?: SendEInvoiceRequest, options?: any): AxiosPromise<SendEInvoiceResponse> {
            return localVarFp.sendEInvoice(companyId, documentId, sendEInvoiceRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Verifies the e-invoice XML format. Checks if all of the mandatory fields are filled and compliant to the right format.
         * @summary Verify e-invoice XML
         * @param {number} companyId The ID of the company.
         * @param {number} documentId The ID of the document.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyEInvoiceXml(companyId: number, documentId: number, options?: any): AxiosPromise<VerifyEInvoiceXmlResponse> {
            return localVarFp.verifyEInvoiceXml(companyId, documentId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * IssuedEInvoicesApi - interface
 * @export
 * @interface IssuedEInvoicesApi
 */
export interface IssuedEInvoicesApiInterface {
    /**
     * Get e-invoice rejection reason
     * @summary Get e-invoice rejection reason
     * @param {number} companyId The ID of the company.
     * @param {number} documentId The ID of the document.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IssuedEInvoicesApiInterface
     */
    getEInvoiceRejectionReason(companyId: number, documentId: number, options?: AxiosRequestConfig): AxiosPromise<GetEInvoiceRejectionReasonResponse>;

    /**
     * Downloads the e-invoice in XML format.
     * @summary Get e-invoice XML
     * @param {number} companyId The ID of the company.
     * @param {number} documentId The ID of the document.
     * @param {boolean} [includeAttachment] Include the attachment to the XML e-invoice.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IssuedEInvoicesApiInterface
     */
    getEInvoiceXml(companyId: number, documentId: number, includeAttachment?: boolean, options?: AxiosRequestConfig): AxiosPromise<string>;

    /**
     * Sends the e-invoice to SDI.
     * @summary Send the e-invoice
     * @param {number} companyId The ID of the company.
     * @param {number} documentId The ID of the document.
     * @param {SendEInvoiceRequest} [sendEInvoiceRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IssuedEInvoicesApiInterface
     */
    sendEInvoice(companyId: number, documentId: number, sendEInvoiceRequest?: SendEInvoiceRequest, options?: AxiosRequestConfig): AxiosPromise<SendEInvoiceResponse>;

    /**
     * Verifies the e-invoice XML format. Checks if all of the mandatory fields are filled and compliant to the right format.
     * @summary Verify e-invoice XML
     * @param {number} companyId The ID of the company.
     * @param {number} documentId The ID of the document.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IssuedEInvoicesApiInterface
     */
    verifyEInvoiceXml(companyId: number, documentId: number, options?: AxiosRequestConfig): AxiosPromise<VerifyEInvoiceXmlResponse>;

}

/**
 * IssuedEInvoicesApi - object-oriented interface
 * @export
 * @class IssuedEInvoicesApi
 * @extends {BaseAPI}
 */
export class IssuedEInvoicesApi extends BaseAPI implements IssuedEInvoicesApiInterface {
    /**
     * Get e-invoice rejection reason
     * @summary Get e-invoice rejection reason
     * @param {number} companyId The ID of the company.
     * @param {number} documentId The ID of the document.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IssuedEInvoicesApi
     */
    public getEInvoiceRejectionReason(companyId: number, documentId: number, options?: AxiosRequestConfig) {
        return IssuedEInvoicesApiFp(this.configuration).getEInvoiceRejectionReason(companyId, documentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Downloads the e-invoice in XML format.
     * @summary Get e-invoice XML
     * @param {number} companyId The ID of the company.
     * @param {number} documentId The ID of the document.
     * @param {boolean} [includeAttachment] Include the attachment to the XML e-invoice.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IssuedEInvoicesApi
     */
    public getEInvoiceXml(companyId: number, documentId: number, includeAttachment?: boolean, options?: AxiosRequestConfig) {
        return IssuedEInvoicesApiFp(this.configuration).getEInvoiceXml(companyId, documentId, includeAttachment, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Sends the e-invoice to SDI.
     * @summary Send the e-invoice
     * @param {number} companyId The ID of the company.
     * @param {number} documentId The ID of the document.
     * @param {SendEInvoiceRequest} [sendEInvoiceRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IssuedEInvoicesApi
     */
    public sendEInvoice(companyId: number, documentId: number, sendEInvoiceRequest?: SendEInvoiceRequest, options?: AxiosRequestConfig) {
        return IssuedEInvoicesApiFp(this.configuration).sendEInvoice(companyId, documentId, sendEInvoiceRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Verifies the e-invoice XML format. Checks if all of the mandatory fields are filled and compliant to the right format.
     * @summary Verify e-invoice XML
     * @param {number} companyId The ID of the company.
     * @param {number} documentId The ID of the document.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IssuedEInvoicesApi
     */
    public verifyEInvoiceXml(companyId: number, documentId: number, options?: AxiosRequestConfig) {
        return IssuedEInvoicesApiFp(this.configuration).verifyEInvoiceXml(companyId, documentId, options).then((request) => request(this.axios, this.basePath));
    }
}
