/**
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol. For more information, please visit https://www.fattureincloud.it.
 *
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { expect } from 'chai'
import { GetExistingReceivedDocumentTotalsResponse } from '../../src/models'

const instance: GetExistingReceivedDocumentTotalsResponse = {
  data: {
    amount_net: 592,
    amount_vat: 20,
    amount_gross: 612,
    amount_withholding_tax: 0,
    amount_other_withholding_tax: 0,
    amount_due: 612,
    payments_sum: 592
  }
}

// beforeEach(function () {
// })

describe('GetExistingReceivedDocumentTotalsResponse', function () {
  it('should create an instance of GetExistingReceivedDocumentTotalsResponse', function () {
    expect(instance).to.be.a('object')
  })

  it('should have the property data (base name: "data")', function () {
    expect(instance.data).to.be.a('object')
  })
})
