/**
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { expect } from "chai";
import { IssuedDocumentType, JoinIssuedDocumentsResponse } from "../../src/models";

 const instance: JoinIssuedDocumentsResponse = {
  data: {
    type: IssuedDocumentType.Invoice
  },
  options: {
    create_from: ["12345", "54321"]
  }
}

beforeEach(function () {
})

describe('JoinIssuedDocumentsResponse', function () {
  it('should create an instance of JoinIssuedDocumentsResponse', function () {
    expect(instance).to.be.a('object');
  })

  it('should have the property data (base name: "data")', function () {
    expect(instance.data).to.be.a('object');
  })

  it('should have the property options (base name: "options")', function () {
    expect(instance.options).to.be.a('object');
  })
})