/**
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { expect } from 'chai';
import { ListF24ResponseAggregation } from '../../src/models';

  var instance: ListF24ResponseAggregation = {
    aggregated_data: {
      amount: 5
    }
  };

  beforeEach(function() {
  });


  describe('ListF24ResponseAggregation', function() {
    it('should create an instance of ListF24ResponseAggregation', function() {
      expect(instance).to.be.a('object');
    });

    it('should have the property aggregatedData (base name: "aggregated_data")', function() {
      expect(instance.aggregated_data).to.be.a('object');
    });

  });

