/* tslint:disable */
/* eslint-disable */
/**
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.1.5
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ClientType } from './client-type';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentMethod } from './payment-method';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentTermsType } from './payment-terms-type';
// May contain unused imports in some cases
// @ts-ignore
import type { VatType } from './vat-type';

export interface Client {
    /**
     * Client id
     */
    'id'?: number | null;
    /**
     * Client code
     */
    'code'?: string | null;
    /**
     * Client name
     */
    'name'?: string | null;
    'type'?: ClientType | null;
    /**
     * Client first name
     */
    'first_name'?: string | null;
    /**
     * Client last name
     */
    'last_name'?: string | null;
    /**
     * Client contact person
     */
    'contact_person'?: string | null;
    /**
     * Client vat number
     */
    'vat_number'?: string | null;
    /**
     * Client tax code
     */
    'tax_code'?: string | null;
    /**
     * Client address street
     */
    'address_street'?: string | null;
    /**
     * Client address postal code
     */
    'address_postal_code'?: string | null;
    /**
     * Client address city
     */
    'address_city'?: string | null;
    /**
     * Client address province
     */
    'address_province'?: string | null;
    /**
     * Client address extra info
     */
    'address_extra'?: string | null;
    /**
     * Client country
     */
    'country'?: string | null;
    /**
     * Client country iso code
     */
    'country_iso'?: string | null;
    /**
     * Client email
     */
    'email'?: string | null;
    /**
     * Client certified email
     */
    'certified_email'?: string | null;
    /**
     * Client phone
     */
    'phone'?: string | null;
    /**
     * Client fax
     */
    'fax'?: string | null;
    /**
     * Client extra
     */
    'notes'?: string | null;
    'default_vat'?: VatType | null;
    /**
     * Client default payment terms
     */
    'default_payment_terms'?: number | null;
    'default_payment_terms_type'?: PaymentTermsType;
    'default_payment_method'?: PaymentMethod;
    /**
     * Client bank name
     */
    'bank_name'?: string | null;
    /**
     * Client bank iban
     */
    'bank_iban'?: string | null;
    /**
     * Client bank swift code
     */
    'bank_swift_code'?: string | null;
    /**
     * Client shipping address
     */
    'shipping_address'?: string | null;
    /**
     * Use e-invoices for this entity
     */
    'e_invoice'?: boolean | null;
    /**
     * Highlight Discount
     */
    'discount_highlight'?: boolean | null;
    /**
     * Client e-invoice code 
     */
    'ei_code'?: string | null;
    /**
     * Client default discount
     */
    'default_discount'?: number | null;
    /**
     * Client has intent declaration
     */
    'has_intent_declaration'?: boolean | null;
    /**
     * Client intent declaration protocol number
     */
    'intent_declaration_protocol_number'?: string | null;
    /**
     * Client intent declaration protocol date
     */
    'intent_declaration_protocol_date'?: string | null;
    /**
     * Price list id
     */
    'price_list_id'?: string | null;
    /**
     * Client creation date
     */
    'created_at'?: string | null;
    /**
     * Client last update date
     */
    'updated_at'?: string | null;
}



