/* tslint:disable */
/* eslint-disable */
/**
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.1.7
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompanyInfoAccessInfo } from './company-info-access-info';
// May contain unused imports in some cases
// @ts-ignore
import type { CompanyInfoPlanInfo } from './company-info-plan-info';
// May contain unused imports in some cases
// @ts-ignore
import type { CompanyType } from './company-type';
// May contain unused imports in some cases
// @ts-ignore
import type { FattureInCloudPlanType } from './fatture-in-cloud-plan-type';

export interface CompanyInfo {
    /**
     * Company id
     */
    'id'?: number | null;
    /**
     * Company name
     */
    'name'?: string | null;
    /**
     * Company email
     */
    'email'?: string | null;
    'type'?: CompanyType;
    'access_info'?: CompanyInfoAccessInfo | null;
    'fic_license_expire'?: string | null;
    'fic_plan_name'?: FattureInCloudPlanType;
    'plan_info'?: CompanyInfoPlanInfo | null;
    /**
     * Company accountant id
     */
    'accountant_id'?: number | null;
    /**
     * Is the logged account an accountant.
     */
    'is_accountant'?: boolean | null;
}



