/* tslint:disable */
/* eslint-disable */
/**
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.1.5
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PriceListPricesType } from './price-list-prices-type';
// May contain unused imports in some cases
// @ts-ignore
import type { PriceListType } from './price-list-type';

/**
 * 
 * @export
 * @interface PriceList
 */
export interface PriceList {
    /**
     * Price list id
     * @type {string}
     * @memberof PriceList
     */
    'id'?: string | null;
    /**
     * Price list name
     * @type {string}
     * @memberof PriceList
     */
    'name'?: string | null;
    /**
     * 
     * @type {PriceListPricesType}
     * @memberof PriceList
     */
    'prices_type'?: PriceListPricesType;
    /**
     * This entity is default
     * @type {boolean}
     * @memberof PriceList
     */
    'is_default'?: boolean | null;
    /**
     * Price list validity start date
     * @type {string}
     * @memberof PriceList
     */
    'valid_from'?: string | null;
    /**
     * Price list validity end date
     * @type {string}
     * @memberof PriceList
     */
    'valid_to'?: string | null;
    /**
     * 
     * @type {PriceListType}
     * @memberof PriceList
     */
    'type'?: PriceListType;
}



